@WebApplication1_HostAddress = http://localhost:8080

### Monitor
GET {{WebApplication1_HostAddress}}/monitor/text/
Accept: application/json

### Snapshot
GET {{WebApplication1_HostAddress}}/snapshot/text/
Accept: application/json